version: '3.6'

services:
  llama-gpt-api:
    image: 'ghcr.io/getumbrel/llama-gpt-api-llama-2-7b-chat:latest'
    environment:
      MODEL: '/models/llama-2-7b-chat.bin'

  llama-gpt-ui:
    image: 'ghcr.io/getumbrel/llama-gpt-ui:latest'
    ports:
      - 9001:9001
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://llama-gpt-api:8000'
      - 'DEFAULT_MODEL=/models/llama-2-7b-chat.bin'
      - 'WAIT_HOSTS=llama-gpt-api:8000'
      - 'WAIT_TIMEOUT=600'
